### ISSUE TITLE
Backlog (Backend)

### ISSUE THREAD

**Issue by CamiloMaca** [FabricaAdso/lisa-back#28]
# Backend
## Diseño
* [x] FabricaAdso/lisa-back#8
* [x] FabricaAdso/lisa-back#13
## Roles y privilegios
* [x] FabricaAdso/lisa-back#1
* [x] FabricaAdso/lisa-back#4
* [x] FabricaAdso/lisa-back#15
## Admin (Pausa)
* [x] FabricaAdso/lisa-back#2
* [x] FabricaAdso/lisa-back#3
* [ ] FabricaAdso/lisa-back#6
* [x] FabricaAdso/lisa-back#9
* [ ] FabricaAdso/lisa-back#20
### Administrador centro de formación
* [ ] FabricaAdso/lisa-back#30
## Gestión de asistencias
* [ ] FabricaAdso/lisa-back#19
* [x] FabricaAdso/lisa-back#21
* [x] FabricaAdso/lisa-back#22
* [ ] FabricaAdso/lisa-back#32
* [ ] FabricaAdso/lisa-back#33
* [ ] FabricaAdso/lisa-back#34
## Reportes
Generar reporte de asistencia tanto por ficha como por aprendiz
* [ ] #37
### Via correo
* [ ] #35
### El aplicativo
* [ ] #36
## Modificaciones a la base de datos
* [x] FabricaAdso/lisa-back#14
* [x] FabricaAdso/lisa-back#18
## Otras tareas
* [ ] FabricaAdso/lisa-back#11
